# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6fdb1203a6ac9db5a96474cf35d0cdedc9575e2b737479a3487902d01dbba5a51f7797b6b042f961d22c4d17fd9cd3e4de2ff4249cdffb6a8fa0c34107b2a53

test:
  secret_key_base: cb7e0424b6ffed66fed60266b9ceaefd80f0d8a77631662cc7a33c310c8f1ab4bd46ca18a44072a4369baa36533986ed5de41dcc18942cc7ad3184ae09ab21e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
